# Generated by Django 5.2.7 on 2025-10-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('cod_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nom_centro', models.CharField(blank=True, max_length=40, null=True)),
                ('ciudad_centro', models.CharField(default='Bogotá', editable=False, max_length=30)),
            ],
            options={
                'db_table': 'centro_formacion',
                
            },
        ),
    ]
