# Generated by Django 5.2.7 on 2025-11-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0002_alter_centro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centro',
            options={'managed': False},
        ),
    ]
