# Generated by Django 5.2.7 on 2025-10-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('cod_amb', models.AutoField(primary_key=True, serialize=False, verbose_name='Código Ambiente')),
                ('nom_amb', models.CharField(max_length=50, verbose_name='Nombre del Ambiente')),
                ('info_amb', models.CharField(max_length=100, verbose_name='Información del Ambiente')),
                ('capacidad_amb', models.IntegerField(verbose_name='Capacidad')),
                ('piso_amb', models.IntegerField(verbose_name='Piso')),
                ('estado_amb', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'En Mantenimiento'), ('ocupado', 'Ocupado'), ('inactivo', 'Inactivo')], max_length=20, verbose_name='Estado')),
                ('imagen_amb', models.ImageField(blank=True, null=True, upload_to='ambientes/', verbose_name='Imagen del Ambiente')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'db_table': 'ambiente',
            },
        ),
    ]
