# Generated by Django 5.2.7 on 2025-11-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambiente',
            options={'managed': False, 'verbose_name': 'Ambiente', 'verbose_name_plural': 'Ambientes'},
        ),
    ]
