# Generated by Django 5.2.7 on 2025-10-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número de Documento')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte')], default='CC', max_length=2, verbose_name='Tipo de Documento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('funcionario', 'Funcionario'), ('instructor', 'Instructor'), ('aprendiz', 'Aprendiz')], max_length=20, verbose_name='Tipo de Usuario')),
                ('cod_coordinacion_fk', models.IntegerField(blank=True, null=True, verbose_name='Coordinación')),
                ('cod_centro_fk', models.IntegerField(blank=True, null=True, verbose_name='Centro')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
