# Generated by Django 5.2.7 on 2025-10-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte')], max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('admin', 'Administrador'), ('funcionario', 'Funcionario')], max_length=20, null=True)),
                ('cod_coordinacion_fk', models.IntegerField(blank=True, null=True)),
                ('cod_centro_fk', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                
            },
        ),
    ]
