# Generated by Django 5.2.7 on 2025-11-24 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0006_reserva_tipos_problema_alter_reserva_estado'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soportes', to='reservas.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soportes', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'soporte',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_soporte', to='usuarios.usuario')),
                ('soporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='soporte.soporte')),
            ],
            options={
                'db_table': 'mensaje_soporte',
                'ordering': ['creado_en'],
            },
        ),
    ]
