# Generated by Django 5.2.7 on 2025-10-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinacion',
            fields=[
                ('cod_coordinacion', models.AutoField(primary_key=True, serialize=False)),
                ('nom_coordinacion', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'coordinacion',
                'managed': False,
            },
        ),
    ]
