# Generated by Django 5.2.7 on 2025-10-31 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0002_alter_centro_options'),
        ('coordinaciones', '0002_alter_coordinacion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinacion',
            name='cod_centro_fk',
            field=models.ForeignKey(
    db_column='cod_centro_fk',
    on_delete=django.db.models.deletion.CASCADE,
    to='centros.centro',
    verbose_name='Centro',
    null=True,
    ),
    ),
    ]
