# Generated by Django 5.2.7 on 2025-10-31 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0002_alter_centro_options'),
        ('coordinaciones', '0003_coordinacion_cod_centro_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinacion',
            name='cod_centro_fk',
            field=models.ForeignKey(db_column='cod_centro_fk', default=1, on_delete=django.db.models.deletion.CASCADE, to='centros.centro', verbose_name='Centro'),
        ),
    ]
