# Generated by Django 5.2.7 on 2025-10-31 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinaciones', '0004_alter_coordinacion_cod_centro_fk'),
    ]

    operations = [
    ]
