# Generated by Django 5.2.7 on 2025-11-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0003_alter_centro_options'),
        ('coordinaciones', '0005_auto_20251030_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinacion',
            name='cod_centro_fk',
            field=models.ForeignKey(db_column='cod_centro_fk', on_delete=django.db.models.deletion.CASCADE, to='centros.centro', verbose_name='Centro'),
        ),
    ]
