# Generated by Django 5.2.7 on 2025-11-06 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0003_reserva_cod_ambiente_fk_reserva_cod_usuario_fk'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReserva',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True)),
                ('cod_reserva_fk', models.ForeignKey(db_column='cod_reserva_fk', on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
                ('id_usuario_fk', models.ForeignKey(db_column='id_usuario_fk', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'historial_reserva',
            },
        ),
    ]
