# Generated by Django 5.2.7 on 2025-10-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_reserva', models.CharField(max_length=100, verbose_name='Título de la Reserva')),
                ('tipo_reserva', models.CharField(choices=[('clase', 'Clase'), ('reunion', 'Reunión'), ('evento', 'Evento'), ('capacitacion', 'Capacitación'), ('examen', 'Examen'), ('otros', 'Otros')], max_length=100, verbose_name='Tipo de Reserva')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_ini', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('motivo', models.CharField(max_length=256, verbose_name='Motivo')),
                ('num_personas', models.IntegerField(verbose_name='Número de Personas')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado')),
            ],
            options={
                'db_table': 'reserva',
                
            },
        ),
    ]
