# Generated by Django 5.2.7 on 2025-10-31 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
        ('reservas', '0002_alter_reserva_options'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cod_ambiente_fk',
            field=models.ForeignKey(db_column='cod_ambiente_fk', default=1, on_delete=django.db.models.deletion.CASCADE, to='ambientes.ambiente', verbose_name='Ambiente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cod_usuario_fk',
            field=models.ForeignKey(db_column='cod_usuario_fk', default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario'),
        ),
    ]
