# Generated by Django 5.2.7 on 2025-11-06 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0002_alter_ambiente_options'),
        ('reservas', '0003_reserva_cod_ambiente_fk_reserva_cod_usuario_fk'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cod_ambiente_fk',
            field=models.ForeignKey(db_column='cod_ambiente_fk', on_delete=django.db.models.deletion.CASCADE, to='ambientes.ambiente', verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cod_usuario_fk',
            field=models.ForeignKey(db_column='cod_usuario_fk', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario'),
        ),
    ]
