# Generated by Django 5.2.7 on 2025-11-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_cod_ambiente_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='comen_admin',
            field=models.CharField(blank=True, db_column='comen_admin', max_length=250, null=True, verbose_name='Comentario administrador'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='comen_funcionario',
            field=models.CharField(blank=True, db_column='comen_funcionario', max_length=250, null=True, verbose_name='Comentario funcionario'),
        ),
    ]
