# Generated by Django 5.2.7 on 2025-11-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_comen_admin_reserva_comen_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipos_problema',
            field=models.CharField(blank=True, db_column='tipos_problema', max_length=200, null=True, verbose_name='Tipos de problema reportados'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('recibida', 'Ambiente recibido'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
